package com.fis.perfcoe.controllers;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.fis.perfcoe.models.UserDTO;
import com.fis.perfcoe.UserRepository;

@RestController
	@RequestMapping("/demo")
	@CrossOrigin("*")
public class UserController {
	
	
		@Autowired // This means to get the bean called userRepository
		           // Which is auto-generated by Spring, we will use it to handle the data
		private UserRepository userRepository;

		@GetMapping(path="/add") // Map ONLY GET Requests
		public @ResponseBody String addNewUser (@RequestParam String name
				, @RequestParam String message) {
			// @ResponseBody means the returned String is the response, not a view name
			// @RequestParam means it is a parameter from the GET or POST request

			UserDTO n = new UserDTO();
			n.setName(name);
			n.setMessage(message);
			userRepository.save(n);
			return "Saved";
		}

		@GetMapping(path="/all")
		public @ResponseBody Iterable<UserDTO> getAllUsers() {
			// This returns a JSON or XML with the users
			return userRepository.findAll();
		}
		
	
}
